import SideNav from './components/SideNav';
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Middas Library",
  description: "Generated by Lucas Benitez",
};
 
export default function Layout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex h-screen flex-col md:flex-row md:overflow-hidden bg-[#fff]">
          <div className="w-full flex-none md:w-64">
            <SideNav />
          </div>
          <div className="flex-grow pt-5 p-2 md:overflow-y-auto">{children}</div>
        </main>
      </body>
    </html>
  );
};